import React from 'react';
import { 
  LayoutDashboard, 
  BookOpen, 
  FileText, 
  Briefcase, 
  Plus, 
  Calendar, 
  Tag, 
  Paperclip, 
  MoreHorizontal,
  ChevronRight,
  CheckCircle2,
  Clock,
  AlertCircle,
  Home,
  Wand2,
  Trash2,
  X,
  Sun,
  Moon,
  Search,
  GanttChart,
  LayoutGrid
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Logbook: BookOpen,
  Report: FileText,
  Project: Briefcase,
  Plus: Plus,
  Calendar: Calendar,
  Tag: Tag,
  Attachment: Paperclip,
  More: MoreHorizontal,
  ChevronRight: ChevronRight,
  Success: CheckCircle2,
  Waiting: Clock,
  Alert: AlertCircle,
  Home: Home,
  AI: Wand2,
  Delete: Trash2,
  Close: X,
  Sun: Sun,
  Moon: Moon,
  Search: Search,
  Gantt: GanttChart,
  Grid: LayoutGrid
};